### Numpy Basics

In [1]:
import numpy as np

In [8]:
data = np.random.randn(2,3)
data

array([[-0.31385387, -0.71940335,  2.21508941],
       [ 0.82363985,  2.05886091, -0.06034036]])

In [3]:
data*10

array([[ 20.03290723,  22.12867972,   7.30415435],
       [ -7.71815614, -10.52113083,  -8.8294497 ]])

In [4]:
data+data

array([[ 4.00658145,  4.42573594,  1.46083087],
       [-1.54363123, -2.10422617, -1.76588994]])

In [5]:
data.shape

(2, 3)

In [6]:
data.dtype

dtype('float64')

In [11]:
type(data)

numpy.ndarray

In [2]:
#upcasting
np.array([1, 2, 3.0])

array([1., 2., 3.])

### Generating Random Numbers

In [22]:
#2 by 3 matrix with random numbers ranging from 0 to 1
#Uniform distribution
np.random.rand(2,3)

array([[0.51157475, 0.14810377, 0.36408911],
       [0.75321608, 0.46453377, 0.20220152]])

In [23]:
#Normal distribution
np.random.randn(4,3)

array([[-0.55445911,  1.00033449, -0.52720548],
       [ 0.3903476 , -1.54490818,  0.41112851],
       [-0.91974667, -0.0912255 , -0.97423716],
       [-0.27142114, -0.08648762, -1.11373997]])

In [26]:
#choose a random number
np.random.randint(1,10)

8

In [25]:
#low, high, # of samples to be drawn
np.random.randint(1,7,20)

array([4, 1, 6, 3, 6, 4, 1, 2, 4, 1, 2, 6, 5, 2, 1, 2, 6, 6, 5, 5])

In [27]:
#random num matrix
np.random.randint(1,100,(4,4))

array([[94, 56, 23, 18],
       [68, 99, 40, 57],
       [90, 12, 42, 33],
       [48, 41,  5,  8]])

### Reshaping

In [29]:
a=np.random.randint(1,100,30)
b=a.reshape(2,3,5)
b

array([[[74, 89, 90, 47, 36],
        [67,  1, 94, 74, 61],
        [79, 95, 17, 30, 32]],

       [[75, 76, 75, 24, 82],
        [65,  8, 29, 95, 31],
        [31, 85, 24, 50, 79]]])

In [31]:
a.shape

(30,)

In [32]:
b.shape

(2, 3, 5)

In [33]:
np.random.randint(1,100,25).reshape(5,5)

array([[68, 88, 88, 27, 19],
       [82, 35, 93,  1, 77],
       [69, 42, 29, 57,  5],
       [52, 73, 34, 53, 37],
       [22, 46, 66,  2, 51]])

### Creating ndarrays

In [7]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [8]:
arr1.shape

(5,)

In [12]:
arr1.dtype

dtype('int32')

In [13]:
type(arr1)

numpy.ndarray

In [9]:
list2 = [[1,2,3,4,5],[6,3,2,2,4]]
arr2 = np.array(list2)
arr2

array([[1, 2, 3, 4, 5],
       [6, 3, 2, 2, 4]])

In [10]:
arr2.ndim

2

In [11]:
arr2.shape

(2, 5)

In [3]:
np.array([1, 2, 3], ndmin=5)

array([[[[[1, 2, 3]]]]])

In [4]:
 np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

### Matrix

In [5]:
#generating matrix
np.mat(np.array([[1, 2],[4,7]]))

matrix([[1, 2],
        [4, 7]])

In [6]:
type(np.mat(np.array([[1, 2],[4,7]])))

numpy.matrix

In [22]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape,sep='') #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int32


In [6]:
#Extract a diagonal
np.diag(x)

array([ 0,  5, 10, 15])

In [7]:
#construct a diagonal array
np.diag(np.diag(x))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])


### Triangular Matrix

In [17]:
#put 1s below the given diag
#3 no. of rows
#5 no. of columns
#1 is subdiagonal, 0 is main diagonal, >0 is above, <0 is below

np.tri(4, 5, 1, dtype=int)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1]])

In [20]:
#1 is subdiagonal, 0 is main diagonal, >0 is above, <0 is below
np.tril([[1,2,3],[4,5,6],[7,8,9]], 0)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [21]:
np.triu([[1,2,3],[4,5,6],[7,8,9]], 0)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

### Generating Zeros/Ones

In [20]:
np.zeros(10)
#returns a new array filled with zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [28]:
np.empty((2,3,2))
#return a new uninitialized array
#it does not bother with the assignment of values
#it just allocates the memory space and while allocation it has garbage values

array([[[1.186e-321, 0.000e+000],
        [0.000e+000, 0.000e+000],
        [0.000e+000, 0.000e+000]],

       [[0.000e+000, 0.000e+000],
        [0.000e+000, 0.000e+000],
        [0.000e+000, 0.000e+000]]])

In [25]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [29]:
np.empty([2,2],dtype=int)

array([[-2052109157,  -785478136],
       [-2119445300,  1890005573]])

In [3]:
mat1 = np.eye(4) 
print("Identity matrix of dimension", mat1.shape)
print(mat1)

Identity matrix of dimension (4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
mat1 = np.eye(4) 
mat1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
type(np.random.randn(2,3))

numpy.ndarray

In [33]:
type(np.empty((2,3)))

numpy.ndarray

### Arange and Linspace

In [35]:
#array range 0 to 19
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [23]:
#evenly spaced values within a given interval
np.arange(5,16,2.3)

array([ 5. ,  7.3,  9.6, 11.9, 14.2])

In [5]:
x = np.arange(16).reshape((-1,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [24]:
print("21 linearly spaced numbers between 1 and 5\n--------------------------------------------")
print((np.linspace(1,5,50)))

21 linearly spaced numbers between 1 and 5
--------------------------------------------
[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


In [25]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

### AsArray

In [13]:
a = [1, 2]
type(a)

list

In [14]:
np.asarray(a)

array([1, 2])

### Copying Array

In [15]:
a = [1, 2]
b=np.array(a, copy=True)
b

array([1, 2])

In [16]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [17]:
y = x
y

array([1, 2, 3])

In [18]:
z = np.copy(x)
z

array([1, 2, 3])

In [19]:
y[0] = 100
y

array([100,   2,   3])

In [20]:
x

array([100,   2,   3])

In [21]:
z

array([1, 2, 3])

### Data Types of ndArrays

In [36]:
arr1 = np.array([1,2,3], dtype=float)

In [38]:
arr1.dtype

dtype('float64')

In [39]:
arr1 = np.array([1,2,3], dtype=int)

In [40]:
arr2.dtype

dtype('int32')

In [41]:
arr = np.array([1,2,3])

In [42]:
arr.dtype

dtype('int32')

In [43]:
arr4=arr.astype(np.float)
arr4.dtype
#astype converts to given datatype

dtype('float64')

In [44]:
arr4

array([1., 2., 3.])

In [45]:
arr

array([1, 2, 3])

In [46]:
abc=np.array(['1.23','-8.5','43'], dtype=np.string_)
abc.astype(float)
#string to float convert

array([ 1.23, -8.5 , 43.  ])

In [47]:
int_array=np.arange(10)
calibers=np.array([.22,.43,.67], dtype=float)
int_array.astype(calibers.dtype)
#int_array will take caliber' dtype

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### Arithmetic with Numpy Arrays

In [49]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [52]:
arr**3

array([[  1,   8,  27],
       [ 64, 125, 216]], dtype=int32)

In [2]:
print(5+np.ones((3,5)))

[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [53]:
arr2=np.array([[9,2,6],[3,5,5]])
arr2>arr1

array([[ True, False,  True],
       [ True,  True,  True]])

### Indexing Slicing

In [34]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr[5]

5

In [36]:
arr[5:8]

array([5, 6, 7])

In [37]:
arr[1:8:2]

array([1, 3, 5, 7])

In [38]:
#elements upto 4th index
arr[:4]

array([0, 1, 2, 3])

In [43]:
arr[-1:5:-1]

array([9, 8, 7, 6])

In [48]:
arr[-1:-5:-1]

array([9, 8, 7, 6])

In [50]:
#Elements at 2nd, 4th, and 6th index
arr[[2,4,6]]

array([2, 4, 6])

In [61]:
arr[5:8] = 90
arr

array([ 0,  1,  2,  3,  4, 90, 90, 90,  8,  9])

In [62]:
arr_slice=arr[5:8]
arr_slice
#starts with 0 (1st place), take 6th place and 8th place

array([90, 90, 90])

In [63]:
arr_slice[1]=45
arr

array([ 0,  1,  2,  3,  4, 90, 45, 90,  8,  9])

In [65]:
arr_slice[:]=64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [71]:
l1=[1,2,3,4,5,6,7]
l1[5]

6

In [70]:
ar=np.array([1,2,3,4,5,6,7])
ar[5]

6

In [51]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [52]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
arr2d[1][1]

5

In [8]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [10]:
arr2d[1,:2]

array([4, 5])

In [11]:
arr2d[:2,2]

array([3, 6])

In [12]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [56]:
#row indices 1 and 2 and column indices 3 and 4
arr2d[0:2,[1,2]]

array([[2, 3],
       [5, 6]])

In [14]:
arr2d[:2,1:]=0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [ ]:
#ch 4,5,7 python for data analysis book

### Subsetting

In [58]:
mat = np.random.randint(1,100,(4,4))
mat>50

array([[ True, False,  True,  True],
       [ True, False,  True,  True],
       [False, False, False, False],
       [ True,  True,  True,  True]])

In [59]:
mat[mat>50]

array([97, 86, 91, 99, 98, 68, 98, 91, 78, 78])

## Boolean Indexing

In [2]:
names = np.array(['Bob','Joe','Wil','Bob','Wil','Joe','Joe'])
data = np.random.randn(7,4)
names

array(['Bob', 'Joe', 'Wil', 'Bob', 'Wil', 'Joe', 'Joe'], dtype='<U3')

In [3]:
data

array([[ 2.06571112, -0.61887394, -0.79056719,  0.60772784],
       [ 1.19446432, -0.91926033, -1.39986788, -0.7071845 ],
       [ 0.04700926, -0.35501502,  2.91654485,  0.09677672],
       [-0.19006367, -0.16713306,  1.04861708, -1.25963402],
       [ 0.15597359,  0.42500236,  0.80734951,  0.25121159],
       [-0.25214261, -1.72615054,  0.70969531, -0.25222838],
       [ 0.6973278 , -0.62745385,  2.13241973,  0.61877076]])

In [4]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [5]:
data[names == 'Bob']

array([[ 2.06571112, -0.61887394, -0.79056719,  0.60772784],
       [-0.19006367, -0.16713306,  1.04861708, -1.25963402]])

In [6]:
data[names == 'Bob',2:]

array([[-0.79056719,  0.60772784],
       [ 1.04861708, -1.25963402]])

In [7]:
data[names == 'Bob',3]

array([ 0.60772784, -1.25963402])

In [8]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [9]:
data[~(names == 'Bob')]

array([[ 1.19446432, -0.91926033, -1.39986788, -0.7071845 ],
       [ 0.04700926, -0.35501502,  2.91654485,  0.09677672],
       [ 0.15597359,  0.42500236,  0.80734951,  0.25121159],
       [-0.25214261, -1.72615054,  0.70969531, -0.25222838],
       [ 0.6973278 , -0.62745385,  2.13241973,  0.61877076]])

In [10]:
cond = names == 'Bob'
data[~cond]

array([[ 1.19446432, -0.91926033, -1.39986788, -0.7071845 ],
       [ 0.04700926, -0.35501502,  2.91654485,  0.09677672],
       [ 0.15597359,  0.42500236,  0.80734951,  0.25121159],
       [-0.25214261, -1.72615054,  0.70969531, -0.25222838],
       [ 0.6973278 , -0.62745385,  2.13241973,  0.61877076]])

In [11]:
cond = names == 'Bob'
data[cond]

array([[ 2.06571112, -0.61887394, -0.79056719,  0.60772784],
       [-0.19006367, -0.16713306,  1.04861708, -1.25963402]])

In [12]:
mask = (names == 'Bob') | (names == 'Will')

In [13]:
mask

array([ True, False, False,  True, False, False, False])

In [14]:
data[mask]

array([[ 2.06571112, -0.61887394, -0.79056719,  0.60772784],
       [-0.19006367, -0.16713306,  1.04861708, -1.25963402]])

In [15]:
data[data < 0] = 0
data

array([[2.06571112, 0.        , 0.        , 0.60772784],
       [1.19446432, 0.        , 0.        , 0.        ],
       [0.04700926, 0.        , 2.91654485, 0.09677672],
       [0.        , 0.        , 1.04861708, 0.        ],
       [0.15597359, 0.42500236, 0.80734951, 0.25121159],
       [0.        , 0.        , 0.70969531, 0.        ],
       [0.6973278 , 0.        , 2.13241973, 0.61877076]])

In [16]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [1.19446432, 0.        , 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.70969531, 0.        ],
       [0.6973278 , 0.        , 2.13241973, 0.61877076]])

## Fancy Indexing

In [30]:
arr=np.empty((8,4))

In [31]:
for i in range(8):
    arr[i]=i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [32]:
arr[[4,3,0,6]]
#fetch row number with index 4,3,0,6

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [33]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [34]:
arr=np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [35]:
arr[[1,5,7,2],[0,3,1,2]]
#index =1, col 0 so value =4 go like this

array([ 4, 23, 29, 10])

In [36]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

## Transposing Arrays

In [38]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [39]:
arr_T=arr.T

In [40]:
arr_T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [41]:
arr=np.random.randn(6,3)
arr

array([[-0.492912  , -0.10231745,  0.12318026],
       [ 1.96195565, -0.38071904,  1.15798752],
       [ 0.15607007,  1.56057701, -0.32325501],
       [ 0.00560806, -1.07117366,  1.40714542],
       [ 0.9980325 , -0.28551812, -0.75977817],
       [ 0.44060396,  1.58089177, -0.67114401]])

In [42]:
np.dot(arr.T,arr)

array([[ 5.30682223, -0.04737742,  1.11465204],
       [-0.04737742,  6.31896885, -3.30930844],
       [ 1.11465204, -3.30930844,  4.46835763]])

In [45]:
np.dot(arr,arr.T)

ValueError: shapes (2,2,4) and (4,2,2) not aligned: 4 (dim 2) != 2 (dim 1)

In [43]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [44]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [46]:
arr
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

### Universal Functions

In [2]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [5]:
x = np.random.randn(8)
y = np.random.randn(8)

In [6]:
x

array([ 0.95062866,  1.00820003,  0.93610015,  0.44891947, -0.21062915,
       -0.66259838, -1.61043743, -0.21548666])

In [7]:
y

array([ 0.60582503,  0.75834716,  1.75652703, -0.32204266, -0.24350034,
        0.12681491,  1.98335718, -0.05232719])

In [8]:
np.maximum(x,y)

array([ 0.95062866,  1.00820003,  1.75652703,  0.44891947, -0.21062915,
        0.12681491,  1.98335718, -0.05232719])

In [9]:
arr=np.random.randn(7)*5
arr

array([-1.34428692,  0.04599426,  7.05482121,  4.75773449,  1.50046944,
       10.89894973,  2.23346065])

In [10]:
fractional_part,whole_part=np.modf(arr)
#modf will filter out into 2 parts  

In [11]:
fractional_part

array([-0.34428692,  0.04599426,  0.05482121,  0.75773449,  0.50046944,
        0.89894973,  0.23346065])

In [12]:
whole_part

array([-1.,  0.,  7.,  4.,  1., 10.,  2.])

In [64]:
mat1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat2 = np.array([[6,4,3],[4,7,1],[7,5,3]])

In [65]:
mat1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
mat2

array([[6, 4, 3],
       [4, 7, 1],
       [7, 5, 3]])

In [67]:
mat1*mat2

array([[ 6,  8,  9],
       [16, 35,  6],
       [49, 40, 27]])

In [69]:
#linear combination
3*mat1-2*mat2

array([[-9, -2,  3],
       [ 4,  1, 16],
       [ 7, 14, 21]])

In [70]:
mat1**3

array([[  1,   8,  27],
       [ 64, 125, 216],
       [343, 512, 729]], dtype=int32)

In [71]:
pow(mat1,3)

array([[  1,   8,  27],
       [ 64, 125, 216],
       [343, 512, 729]], dtype=int32)

### Mathematical and Statistical Models

In [13]:
arr=np.random.randn(5,4)
arr


array([[-0.58139614,  0.66586936,  0.64108422,  0.59889849],
       [ 1.88303885,  0.3794434 ,  0.75379381,  0.98852209],
       [-1.79625833, -1.36409087,  0.24675554,  2.51016937],
       [-0.74663302, -0.14919256,  1.02492622,  0.69931956],
       [ 1.79989473, -1.19611457,  1.03038889, -0.23136165]])

In [14]:
arr.mean()

0.3578528700288896

In [15]:
np.mean(arr)

0.3578528700288896

In [16]:
arr.sum()

7.157057400577792

In [17]:
np.sum(arr)

7.157057400577792

In [18]:
np.std(arr)

1.0857946374613618

In [19]:
arr.mean(axis=1)

array([ 0.33111398,  1.00119954, -0.10085607,  0.20710505,  0.35070185])

In [20]:
arr.sum(axis=0)

array([ 0.5586461 , -1.66408524,  3.69694868,  4.56554786])

In [21]:
arr=np.array([0,1,2,3,4,5,6,7])
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [23]:
arr=np.array([[0,1,2],[3,4,5],[6,7,8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
arr.cumsum(axis=0)
#2+5=7,2+5+8=15

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [25]:
arr.cumsum(axis=1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]], dtype=int32)

### Methods for Boolean Arrays

In [26]:
arr=np.random.randn(100)
arr

array([ 0.02005253, -1.26699203, -0.04818863,  1.33822307,  0.55534547,
        1.52794616,  0.13102174,  0.49580097, -1.11538183,  0.87119328,
       -2.5692452 ,  1.44311063,  0.10631795, -0.18583297, -0.18294734,
        0.09991589, -0.17085846,  1.50049063,  0.05250197, -1.23811615,
       -0.34643239, -1.25360488, -0.62030921, -1.51687039, -0.24117491,
       -1.08588952, -0.7013334 ,  0.54948366, -0.5974176 , -2.09816397,
       -1.49790348,  0.1184652 , -0.66888265, -0.58751615, -0.52328214,
        0.10350444, -1.25540849,  1.05723432, -0.2195564 ,  1.24654821,
        0.46799858,  1.37383706, -0.58884825, -0.60412289, -0.02412687,
       -2.06263887,  0.99445715, -1.28754186, -0.66966937,  0.84978992,
        1.08763746,  0.73568664, -0.54280068, -1.44427844,  0.96568139,
       -1.06516449, -1.09683447, -1.96176445,  0.12903423,  0.16190954,
        0.04092237, -0.87007997, -0.25173435, -1.5383345 ,  0.0211648 ,
       -0.649067  ,  0.11348907,  0.03999838,  1.21322698, -0.40

In [27]:
(arr>0).sum() #No of positive values

47

In [28]:
bools = np.array([False,False,True,True])

In [29]:
bools.any() #if any oneof the values have True

True

In [30]:
bools.all() #if all the values have True

False

### Sorting

In [31]:
arr=np.random.randn(6)
arr

array([-0.20950953,  0.17590844, -1.72389082,  1.03430805, -0.42798135,
       -0.46696548])

In [32]:
arr.sort()

In [33]:
arr

array([-1.72389082, -0.46696548, -0.42798135, -0.20950953,  0.17590844,
        1.03430805])

In [34]:
arr=np.random.randn(5,3)
arr

array([[ 1.1415171 , -0.58909347,  0.04661441],
       [-0.36166237,  0.03945016, -0.92543055],
       [ 0.2915814 , -0.59942613,  0.27555018],
       [-1.19745029,  0.23863166, -0.93217461],
       [ 1.26242162, -0.18432196,  0.44074622]])

In [35]:
arr.sort(1) #sort according to column

In [36]:
arr

array([[-0.58909347,  0.04661441,  1.1415171 ],
       [-0.92543055, -0.36166237,  0.03945016],
       [-0.59942613,  0.27555018,  0.2915814 ],
       [-1.19745029, -0.93217461,  0.23863166],
       [-0.18432196,  0.44074622,  1.26242162]])

In [39]:
large_arr=np.random.randn(1000)
large_arr.sort()

In [40]:
large_arr[int(0.05*len(large_arr))] #5% quantile - only 5% values are less than that and 95% greater than that

-1.5331786020798877

### Unique and Other Set Logic

In [41]:
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [42]:
ints=np.array([3,3,3,2,2,1,1,4,4])
np.unique(ints)

array([1, 2, 3, 4])

In [43]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [44]:
values=np.array([6,0,0,3,2,5,6])
np.in1d(values,[2,3,6])
#if value present return True
#in 1 dimension array

array([ True, False, False,  True,  True, False,  True])

### File Input and Output with Arrays

In [45]:
arr=np.arange(10)
np.save('some_array',arr)

In [46]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.savez('array_archive.npz',a=arr,b=arr)

In [48]:
arch = np.load('array_archive.npz')
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
arch['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.savez_compressed('array_archive.npz',a=arr,b=arr)